name: Bug Report
description: Report a bug in the website, validation, or framework
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the information below.

  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Type
      description: What type of bug is this?
      options:
        - Website UI/UX issue
        - Data validation error
        - Incorrect evaluation data
        - Build/deployment issue
        - Documentation issue
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of the bug
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Error Messages
      description: Add screenshots or paste error messages

  - type: input
    id: browser
    attributes:
      label: Browser/Environment
      description: What browser or environment are you using?
      placeholder: "e.g., Chrome 120, Firefox 115, Node 18"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
